SearchBayesianSkopt: Config 0 Exception. Config: {'topK': 145, 'shrink': 963, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 1 Exception. Config: {'topK': 785, 'shrink': 971, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 2 Exception. Config: {'topK': 625, 'shrink': 282, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 3 Exception. Config: {'topK': 319, 'shrink': 466, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 4 Exception. Config: {'topK': 298, 'shrink': 917, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 5 Exception. Config: {'topK': 979, 'shrink': 22, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 6 Exception. Config: {'topK': 11, 'shrink': 4, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 7 Exception. Config: {'topK': 980, 'shrink': 2, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 8 Exception. Config: {'topK': 959, 'shrink': 997, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 9 Exception. Config: {'topK': 19, 'shrink': 977, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 10 Exception. Config: {'topK': 12, 'shrink': 4, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 11 Exception. Config: {'topK': 23, 'shrink': 4, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 12 Exception. Config: {'topK': 998, 'shrink': 11, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 13 Exception. Config: {'topK': 971, 'shrink': 1000, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 14 Exception. Config: {'topK': 990, 'shrink': 27, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 15 Exception. Config: {'topK': 29, 'shrink': 992, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 16 Exception. Config: {'topK': 975, 'shrink': 992, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 17 Exception. Config: {'topK': 19, 'shrink': 980, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 18 Exception. Config: {'topK': 8, 'shrink': 20, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 19 Exception. Config: {'topK': 990, 'shrink': 2, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 20 Exception. Config: {'topK': 982, 'shrink': 993, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 21 Exception. Config: {'topK': 6, 'shrink': 8, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 22 Exception. Config: {'topK': 989, 'shrink': 1000, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 23 Exception. Config: {'topK': 31, 'shrink': 988, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 24 Exception. Config: {'topK': 996, 'shrink': 4, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 25 Exception. Config: {'topK': 8, 'shrink': 33, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 26 Exception. Config: {'topK': 1000, 'shrink': 990, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 27 Exception. Config: {'topK': 25, 'shrink': 5, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 28 Exception. Config: {'topK': 10, 'shrink': 992, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 29 Exception. Config: {'topK': 989, 'shrink': 2, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 30 Exception. Config: {'topK': 24, 'shrink': 984, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 31 Exception. Config: {'topK': 983, 'shrink': 5, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 32 Exception. Config: {'topK': 994, 'shrink': 995, 'similarity': 'cosine', 'normalize': False, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 33 Exception. Config: {'topK': 7, 'shrink': 8, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 34 Exception. Config: {'topK': 963, 'shrink': 989, 'similarity': 'cosine', 'normalize': True, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Search complete. Best config is None: None
