SearchBayesianSkopt: Config 0 Exception. Config: {'topK': 715, 'shrink': 523, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 1 Exception. Config: {'topK': 902, 'shrink': 950, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 2 Exception. Config: {'topK': 109, 'shrink': 496, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 3 Exception. Config: {'topK': 395, 'shrink': 67, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 4 Exception. Config: {'topK': 55, 'shrink': 337, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 5 Exception. Config: {'topK': 979, 'shrink': 999, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 6 Exception. Config: {'topK': 990, 'shrink': 16, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 7 Exception. Config: {'topK': 11, 'shrink': 993, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 8 Exception. Config: {'topK': 7, 'shrink': 10, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 9 Exception. Config: {'topK': 973, 'shrink': 0, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 10 Exception. Config: {'topK': 16, 'shrink': 996, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 11 Exception. Config: {'topK': 993, 'shrink': 992, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 12 Exception. Config: {'topK': 13, 'shrink': 4, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 13 Exception. Config: {'topK': 998, 'shrink': 15, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 14 Exception. Config: {'topK': 6, 'shrink': 984, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 15 Exception. Config: {'topK': 992, 'shrink': 983, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 16 Exception. Config: {'topK': 26, 'shrink': 0, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 17 Exception. Config: {'topK': 977, 'shrink': 9, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 18 Exception. Config: {'topK': 23, 'shrink': 995, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 19 Exception. Config: {'topK': 983, 'shrink': 989, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 20 Exception. Config: {'topK': 7, 'shrink': 16, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 21 Exception. Config: {'topK': 998, 'shrink': 4, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 22 Exception. Config: {'topK': 5, 'shrink': 994, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 23 Exception. Config: {'topK': 983, 'shrink': 993, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 24 Exception. Config: {'topK': 10, 'shrink': 7, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 25 Exception. Config: {'topK': 994, 'shrink': 3, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 26 Exception. Config: {'topK': 13, 'shrink': 987, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 27 Exception. Config: {'topK': 1000, 'shrink': 965, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 28 Exception. Config: {'topK': 10, 'shrink': 1, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 29 Exception. Config: {'topK': 998, 'shrink': 12, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 30 Exception. Config: {'topK': 7, 'shrink': 992, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 31 Exception. Config: {'topK': 962, 'shrink': 1000, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 32 Exception. Config: {'topK': 10, 'shrink': 15, 'similarity': 'dice', 'normalize': False} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 33 Exception. Config: {'topK': 999, 'shrink': 7, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 34 Exception. Config: {'topK': 994, 'shrink': 995, 'similarity': 'dice', 'normalize': True} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Search complete. Best config is None: None
